server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: 'true'

#consumer:
#  api:
#    url: http://localhost:8081/
#
#producer:
#  api:
#    url: http://localhost:8082/

eureka:
  client:
    instance:
      preferIpAddress: 'true'
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    status-page-url-path: /actuator/health
    hostname: localhost

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: consumer-microservice
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/consumer/**
#        - id: producer-microservice
#          uri: http://localhost:8082/
#          filters:
#            - name: Retry
#              args:
#                retries: 3
#                statuses: BAD_GATEWAY
#                methods: GET,POST
#                backoff:
#                  firstBackoff: 10ms
#                  maxBackoff: 50ms
#                  factor: 2
#                  basedOnPreviousValue: false
#          predicates:
#            - Path=/producer/**
