version: '3.2'

services:
  string-consumer:
    container_name: string-consumer
    image: lrochadev/string-consumer
    build:
      context: ./string-consumer
    ports:
      - 8080:8080
    environment:
      - "JAVA_OPTIONS=-XX:MaxRAMPercentage=80 -Dserver.port=8080 -Dspring.profiles.active=prod"
    networks:
      - production-network
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 768M
            reservations:
              cpus: '0.25'
              memory: 256M

  string-producer:
    container_name: string-producer
    image: lrochadev/string-producer
    build:
      context: ./string-producer
    ports:
      - 8081:8081
    environment:
      - "JAVA_OPTIONS=-XX:MaxRAMPercentage=80 -Dserver.port=8081 -Dspring.profiles.active=prod"
    networks:
      - production-network

networks:
  production-network:
    name: production-network
    driver: bridge
