version: '3.2'

services:
  eureka-server:
    container_name: eureka-server
    image: lrochadev/eureka-server
    restart: always
    network_mode: host
    build:
      context: ./eureka-server
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTIONS=-XX:MaxRAMPercentage=80
      - SPRING_PROFILES_ACTIVE=prod
  
  gateway:
    container_name: gtw
    image: lrochadev/gateway
    restart: always
    network_mode: host
    build:
      context: ./spring-cloud-gateway
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTIONS=-XX:MaxRAMPercentage=80
      - EUREKA_SERVICE_URL=http://192.168.1.3:8761/eureka
    depends_on:
      - eureka-server

  string-consumer:
    image: lrochadev/string-consumer
    restart: always
    network_mode: host
    build:
      context: ./string-consumer
    expose:
      - 8081
    environment:
      - JAVA_OPTIONS=-XX:MaxRAMPercentage=80
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVICE_URL=http://192.168.1.3:8761/eureka
    depends_on:
      - eureka-server
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M

  string-producer:
    container_name: string-producer
    image: lrochadev/string-producer
    restart: always
    network_mode: host
    build:
      context: ./string-producer
    ports:
      - 8082:8082
    environment:
      - JAVA_OPTIONS=-XX:MaxRAMPercentage=80
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVICE_URL=http://192.168.1.3:8761/eureka
    depends_on:
      - eureka-server
