version: '3.2'

services:
  eureka-server:
    container_name: eureka-server
    image: lrochadev/eureka-server
    build:
      context: ./eureka-server
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTIONS=-XX:MaxRAMPercentage=80
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - production-network
  
  string-consumer:
    container_name: string-consumer
    image: lrochadev/string-consumer
    build:
      context: ./string-consumer
    ports:
      - 8081:8081
    environment:
      - JAVA_OPTIONS=-XX:MaxRAMPercentage=80
      - SPRING_PROFILES_ACTIVE=prod
      # - EUREKA_SERVICE_URL=http://192.168.0.111:8761/eureka
    networks:
      - production-network
    depends_on:
      - eureka-server
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 768M
            reservations:
              cpus: '0.25'
              memory: 256M

  string-producer:
    container_name: string-producer
    image: lrochadev/string-producer
    build:
      context: ./string-producer
    ports:
      - 8082:8082
    environment:
      - JAVA_OPTIONS=-XX:MaxRAMPercentage=80
      - SPRING_PROFILES_ACTIVE=prod
      # - EUREKA_SERVICE_URL=http://192.168.0.111:8761/eureka
    networks:
      - production-network
    depends_on:
      - eureka-server

networks:
  production-network:
    name: production-network
    driver: bridge
