spring:
  cloud:
    discovery:
      enabled: 'false'
  zipkin:
    enabled: 'false'
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    max-active: 10
#    initial-size: 5
#    max-idle: 5
#    min-idle: 1
#    test-while-idle: true
#    test-on-borrow: true
#    validation-query: SELECT 1
#    url: jdbc:sqlserver://localhost:1401;databaseName=xxx;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: xxx
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        generate_statistics: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  sqlserver:
    datasource:
      host-name: localhost
      port: 1401
      url: jdbc:sqlserver://${app.sqlserver.datasource.host-name}:${app.sqlserver.datasource.port};databaseName=xxx;encrypt=true;trustServerCertificate=true
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: xxx
      validation-query: SELECT 1
      validation-interval: 30000
      time-between-eviction.runs-millis: 30000
      max-active: 200
      min-idle: 10
      max-wait: 10000
      initial-size: 10
      remove-abandoned-timeout: 7200
      min-evictable-idle-time-millis: 30000
      suspect-timeout: 7200
      remove-abandoned: true
      test-on-borrow: true